version: "3.1"

services:

  db:
    restart: always
    image: postgres
    container_name: postgres_foodgram
    environment:
      - POSTGRES_USER=foodgram
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=foodgram
      - POSTGRES_PORT=5432
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  pgadmin:
      image: dpage/pgadmin4
      container_name: pgadmin4_v2
      depends_on:
        - db
      ports:
        - "5051:80"
      environment:
        PGADMIN_DEFAULT_EMAIL: admin@admin.ru
        PGADMIN_DEFAULT_PASSWORD: 12345
      restart: always


volumes:
  postgres_data:

